### ISSUE TITLE
Add Subscribe method to EpochManager

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#105]
#### Context
- As introduced in Epoch #102, `EpochManager` should allow other components to subscribe to checkpoint notifications. That is, receiving a message every time an epoch is over and the next is started.
- It should also allow other components to subscribe to specific checkpoints. That is, receiving a message once a particular epoch is over or it just started.

#### Actionables
- [ ] Create a recurrent task that ticks exactly at the checkpoints (classical delta correction should be enough to compensate the typical skew of scheduled tasks).
- [ ] Add a `schedule` map to the main structure of the `EpochManager` library (`HashMap<u32, Payload>`). `Payload` should be the union of typical payload types (likely implemented as of #107 ).
- [ ] Add a `Subscribe` handler to `EpochManager` that will take a checkpoint number and a payload. It should append the payload and the caller actor's address to an array as an entry of the `schedule` map using the checkpoint number as key.
- [ ] If no `checkpoint` is specified when calling `Subscribe`, a constant key should be used (e.g.: `every`).
- [ ] Make the recurrent task access the `schedule` map and make a call to every of its entry's address attaching the associated payload and using some `EpochNotify{checkpoint, payload}` message (see #107).
- [ ] For every tick of the recurrent task, the `every` constant key in the `schedule` map should also be accessed and make a call to every of its entry's address attaching the associated payload and using some `EpochNotify(checkpoint, payload)` message (see #107).
- [ ] Incorporate `Subscribe` and `EpochNotify` to the project documentation (mkdocs).
- [ ] Create a PR and link it to this issue
