### ISSUE TITLE
Storage Manager

### ISSUE THREAD

**Issue by mmartinbar** [witnet/witnet-rust#30]
#### Description
The storage manager will be the actor in charge of wrapping up the functionality implemented in the `storage`library.

The state of the storage actor will be an instance of the RocksDB storage, defined in the storage library.

The messages the storage manager actor will receive are:
- Get(key) -> call `get` storage method and return whatever that method returns
- Put(key, value) -> call `put` storage method and return whatever that method returns
- Delete(key) -> call `delete`storage method and return whatever that method returns

#### Actionables
- [x] Storage library functionality (already done by @aesedepece )
- [x] Storage library unit tests (already done by @aesedepece )
- [x] Storage manager actor wrapper: state initialization & message handlers
- [x] Integrate storage manager creation in main
- [x] Storage manager actor documentation (state & messages)
