### ISSUE TITLE
Peers Manager

### ISSUE THREAD

**Issue by mariocao** [witnet/witnet-rust#31]
#### Description
The peers manager will provide the functionality of managing a set of available peers known to the Witnet node, so that other actors may add, remove and retrieve peers. The manager will be an actor in charge of wrapping up the functionality provided by a `peers library`.

The messages the peers manager actor will receive are:
- Add(peer) -> call `add` peer method and return whatever that method returns (it can be used to refresh the peer info if the peer already exists)
- Remove(peer) -> call `remove` method and return whatever that method returns
- Get(peer) -> call `get` peer method and return whatever that method returns

#### Actionables
- [x] Peers library functionality
- [x] Peers library unit tests
- [x] Peers manager actor wrapper: state initialization & message handlers
- [x] Integrate peers manager creation in main
- [x] Peers manager actor documentation (state & messages)
- [ ] Improve the `peer selection algorithm` to make sure that no (localized) attacker can fill the entire table with  nodes/addresses (e.g. with IP buckets as in Bitcoin core)
