### ISSUE TITLE
Connections Manager

### ISSUE THREAD

**Issue by kronolynx** [witnet/witnet-rust#33]
#### Description

The connection manager is an Actor wrapping a Node that contains a TCP server and that can open multiple TCP clients(peers).

#### Messages
- CreateConnection -> received from SessionManager

#### Messages sent to other actors
- NewConnection(inbound|outbound) -> send to SessionManager
- GetPeer -> send to PeerManager in order to retrieve a new peer address (see #37)

#### Actionables
- [ ] Accept TCP connections from peers
- [ ] Open TCP connections to peers
- [ ] Close connections
- [ ] Define frame header
- [ ] Handle byte framing using header
- [ ] Connection manager unit tests
- [ ] Connection manager documentation
